var searchData=
[
  ['a_20custom_20analysis_20subroutine_0',['Writing a custom analysis subroutine',['../md_doc_2analysis.html',1,'']]],
  ['a_20new_20problem_1',['Setting up a new problem',['../md_doc_2amrvacusr.html',1,'']]],
  ['a_20physics_20module_20to_20mpi_20amrvac_2',['Adding a physics module to MPI-AMRVAC',['../md_doc_2addmodule.html',1,'']]],
  ['about_20the_20mpi_20amrvac_20documentation_3',['About the MPI-AMRVAC documentation',['../md_doc_2documentation.html',1,'']]],
  ['acknowledgments_4',['Acknowledgments',['../md_doc_2acknowledgments.html',1,'']]],
  ['adaptive_20mesh_20refinement_5',['Adaptive Mesh Refinement',['../md_doc_2amrstructure.html',1,'']]],
  ['adding_20a_20physics_20module_20to_20mpi_20amrvac_6',['Adding a physics module to MPI-AMRVAC',['../md_doc_2addmodule.html',1,'']]],
  ['advection_20reaction_20diffusion_20module_7',['Advection-reaction-diffusion module',['../md_doc_2advection__reaction__diffusion.html',1,'']]],
  ['alfven_20wing_20test_20problem_8',['Alfven wing test problem',['../md_tests_2mhd_2alfvenwing__3D_2alfvenwing.html',1,'']]],
  ['amrvac_9',['amrvac',['../md_doc_2addmodule.html',1,'Adding a physics module to MPI-AMRVAC'],['../md_doc_2dust.html',1,'Dust in MPI-AMRVAC'],['../md_doc_2publications.html',1,'Publications related to MPI-AMRVAC'],['../md_doc_2radiative__cooling.html',1,'Radiative cooling in MPI-AMRVAC'],['../md_doc_2smallvalues.html',1,'Small values options in MPI-AMRVAC'],['../md_doc_2thermal__conduction.html',1,'Thermal conduction in MPI-AMRVAC']]],
  ['amrvac_203_200_20demo_20simulations_10',['MPI-AMRVAC 3.0 Demo simulations',['../md_doc_2demo-movies.html',1,'']]],
  ['amrvac_20and_20its_20documentation_11',['Contributing to MPI-AMRVAC and its documentation',['../md_doc_2contributing.html',1,'']]],
  ['amrvac_20data_20file_20format_12',['MPI-AMRVAC data file format',['../md_doc_2fileformat.html',1,'']]],
  ['amrvac_20datasets_20and_20yt_13',['AMRVAC datasets and YT',['../md_doc_2yt__usage.html',1,'']]],
  ['amrvac_20documentation_14',['About the MPI-AMRVAC documentation',['../md_doc_2documentation.html',1,'']]],
  ['analysis_20subroutine_15',['Writing a custom analysis subroutine',['../md_doc_2analysis.html',1,'']]],
  ['and_20equations_16',['Physics modules and equations',['../md_doc_2equations.html',1,'']]],
  ['and_20its_20documentation_17',['Contributing to MPI-AMRVAC and its documentation',['../md_doc_2contributing.html',1,'']]],
  ['and_20translational_20symmetry_18',['Using axial and translational symmetry',['../md_doc_2axial.html',1,'']]],
  ['and_20yt_19',['AMRVAC datasets and YT',['../md_doc_2yt__usage.html',1,'']]],
  ['asked_20questions_20',['Frequently Asked Questions',['../md_doc_2faq.html',1,'']]],
  ['at_20line_20integrated_20quantities_21',['Looking at line-integrated quantities',['../md_doc_2collapsed.html',1,'']]],
  ['auxiliary_20variables_20nw_22',['Auxiliary variables (nw...)',['../md_doc_2mpiamrvac__nw.html',1,'']]],
  ['axial_20and_20translational_20symmetry_23',['Using axial and translational symmetry',['../md_doc_2axial.html',1,'']]]
];
