#########################################################################
# Here we have some auxilary modules
#########################################################################
FOBJECTS += mod_timing.t mod_odeint.t mod_oneblock.t mod_lu.t mod_Knuth_random.t
