#########################################################################
# Here we have some auxilary modules
#########################################################################
FOBJECTS += mod_timing.t mod_odeint.t mod_oneblock.t mod_math.t mod_qr.t mod_lu.t mod_lnsrch.t mod_random.t mod_interpolation.t mod_rootfinding.t mod_lookup_table.t
