#########################################################################
# Here we have some auxilary modules
#########################################################################
FOBJECTS += mod_timing.t mod_odeint.t mod_oneblock.t mod_lu.t mod_random.t mod_interpolation.t mod_point_searching.t mod_trace_Vfield.t
