FOBJECTS += mod_physics.t mod_physics_roe.t mod_physics_hllc.t mod_physics_ppm.t
FOBJECTS += mod_thermal_conduction.t mod_radiative_cooling.t mod_dust.t mod_viscosity.t mod_gravity.t
FOBJECTS += mod_lfff.t mod_pfss.t mod_tdfluxrope.t mod_magnetofriction.t mod_dipole.t

