# Add the objects for MHD:

FOBJECTS += hall$F divb$F correctaux$F roe$F mhdhllc$F hlld$F mhdhlld$F fill_gridvars$F fct$F eigensystem$F
OBJECTS += hall.o divb.o correctaux.o roe.o mhdhllc.o hlld.o mhdhlld.o fill_gridvars.o fct.o eigensystem.o
