ifndef AMRVAC_DIR
    $(error The AMRVAC_DIR environment variable needs to be defined.)
endif

#AMRVAC_DIR=/users/cpa/haow/codes/AGILE-experimental

include $(AMRVAC_DIR)/make/include-all.mk

all: amrvac
	
