INCLUDES += mod_forest.t      
FOBJECTS += amr_grid.t coarsen.t mod_coarsen_refine.t refine.t \
errest.t selectgrids.t \
amr_neighbors.t forest.t mod_load_balance.t \
amr_solution_node.t mod_amr_fct.t mod_space_filling_curve.t \

