INCLUDES += mod_forest.t
FOBJECTS += mod_amr_grid.t mod_coarsen.t mod_coarsen_refine.t mod_refine.t \
mod_errest.t mod_selectgrids.t \
mod_amr_neighbors.t mod_functions_forest.t mod_load_balance.t \
mod_amr_solution_node.t mod_amr_fct.t mod_space_filling_curve.t \
mod_initialize_amr.t

