#undefine EPSINF
#define GLM
#undefine HALL
#undefine UCONVERT
#undefine SAVENOW
#undefine TRANSFORMW
#undefine RAY
#undefine BIGENDIAN
#undefine FOURTHORDER
#undefine TCRKL2
#undefine SPECIALTOLERANCE
#undefine MAGNETOFRICTION
#define PARTICLES
#define PARTICLES_GCA
