#########################################################################
# Everything IO-related goes here:
#########################################################################
FOBJECTS += mod_input_output_helper.t mod_input_output.t mod_convert.t mod_convert_files.t mod_collapse.t mod_slice.t mod_calculate_xw.t
