#########################################################################
# Everything IO-related goes here:
#########################################################################
FOBJECTS += mod_input_output.t convert.t mod_collapse.t mod_slice.t mod_calculate_xw.t
