#!/bin/csh -f

# script to collect a series of idl output frames from amrvac convert stage into
# one large file, for animation with idl scripts
# four arguments: filenamebase, begin and end number, skiprate

if($#argv != 4) then
 echo "Usage: $0 filenamebase startindex stopindex skipindex"
 goto done
endif

if ("$argv[2]">"$argv[3]") then
 echo "startindex $2 is larger than stopindex $3"
 goto done
endif


echo "filenamebase given is" $argv[1]
echo " will catenate files: "
seq -f $argv[1]%04g.out $argv[2] $argv[4] $argv[3]
echo " all will be gathered in " $argv[1]all.out
cat `seq -f $argv[1]%04g.out $argv[2] $argv[4] $argv[3]` > $argv[1]all.out
exit 0

done:
 exit 0
