#!/bin/csh -f
#usage: dq
#aim: to list data related to the current amrvac.par 
set ful=`ls -l amrvac.par`
set fname=$ful[$#ful]
if (-e $fname ) then
   goto step1
else
   echo "$1 is not an existing parfilename"
   goto done
endif
step1:
set linedata=`sed 's/[[:space:]]//g' $fname | sed -n '/\&filelist/,$ {/^filenameout/=}'`
set linedata=`echo $linedata | awk '{print $1}'`
set dataname=`sed -n "$linedata p;$linedata q" $fname | awk -F\' '{print $2}'`
ls $dataname*
done:
exit 0
error:
exit 1
