#!/bin/csh -f
#usage: dq
#aim: to list data related to the current amrvac.par 
set ful=`ls -l amrvac.par`
set fname=$ful[$#ful]
if (-e $fname ) then
   goto step1
else
   echo "$1 is not an existing parfilename"
   goto done
endif
step1:
set linedata=`sed 's/[[:space:]]//g' $fname | sed -n -e '/\&filelist/,$ {' -e '/^base_filename/=' -e '}'`
set linedata=`echo $linedata | awk '{print $1}'`
set dataname=`sed -n -e "$linedata p" -e "$linedata q" $fname | awk -F\' '{print $2}'`
ls $dataname*.vtu $dataname*.dat $dataname*.log $dataname*.blk $dataname*.vti $dataname*.pvtu $dataname*.out $dataname*.plt
done:
exit 0
error:
exit 1
