#!/bin/csh -f
#usage: rmdata
#aim: to remove data related to the current amrvac.par or argument xxxx.par
if($#argv == 0) then
  set ful=`ls -l amrvac.par`
endif
if($#argv == 1) then
  set ful=`ls -l $argv[1]`
endif
set fname=$ful[$#ful]
if (-e $fname ) then
   goto step1
else
   echo "$1 is not an existing parfilename"
   goto done
endif
step1:
set linedata=`sed 's/[[:space:]]//g' $fname | sed -n -e '/\&filelist/,$ {' -e '/^base_filename/=' -e '}'`
set linedata=`echo $linedata | awk '{print $1}'`
set dataname=`sed -n -e "$linedata p" -e "$linedata q" $fname | awk -F\' '{print $2}'`
set datacount=`ls $dataname*.dat | grep -c '.dat'`
if($datacount < 1 ) then
 echo "Data "$dataname"*.dat are not found!"
 goto done
endif

ls $dataname*.vtu $dataname*.dat $dataname*.log $dataname*.blk $dataname*.vti $dataname*.pvtu $dataname*.out $dataname*.plt $dataname*.csv
echo -n "Are you sure to delete data above? (y to delete)"
set yn=$<
if ($yn == "y") then
 rm -f $dataname*.vtu $dataname*.dat $dataname*.log $dataname*.blk $dataname*.vti $dataname*.pvtu $dataname*.out $dataname*.plt $dataname*.csv
endif
done:
exit 0
error:
exit 1
