#!/bin/csh -f
# usage: tailvac
# aim: to monitor .log file
if($#argv == 0) then
  set ful=`ls -l amrvac.par`
endif
if($#argv == 1) then
  set ful=`ls -l $argv[1]`
endif
set fname=$ful[$#ful]
if (-e $fname ) then
   goto step1
else
   echo "$1 is not an existing parfilename"
   goto done
endif
step1:
set datadir=`grep "base_filename" $fname`
set dataname=`echo $datadir | awk -F\' '{print $2}'`
set datalog=$dataname".log"
tail $datalog
echo
done:
exit 0
error:
exit 1
