#undefine EPSINF
#undefine GLM
#undefine FCT
#undefine HALL
#undefine UCONVERT
#undefine SAVENOW
#undefine TRANSFORMW
#undefine RAY
#undefine BIGENDIAN
#undefine FOURTHORDER
#undefine TCRKL2
#undefine TCPERPENDICULAR
#undefine SPECIALTOLERANCE
#undefine MAGNETOFRICTION
#undefine PARTICLES
#undefine PARTICLES_ADVECT
#undefine PARTICLES_GCA
#undefine PARTICLES_LORENTZ
#undefine PARTICLES_USER
#undefine BOUNDARYDRIVER
#undefine PROCESSGLOBAL
#undefine SAVEGHOSTCELL
#undefine STRETCHGRID
#undefine EVOLVINGBOUNDARY
