#undefine EPSINF
#undefine GLM
#undefine FCT
#undefine HALL
#undefine UCONVERT
#undefine RAY
#undefine BIGENDIAN
#undefine FOURTHORDER
#undefine TCRKL2
#undefine MAGNETOFRICTION
#undefine PARTICLES
#undefine PARTICLES_ADVECT
#undefine PARTICLES_GCA
#undefine PARTICLES_LORENTZ
#undefine PARTICLES_USER
#undefine BOUNDARYDRIVER
#undefine PROCESSGLOBAL
#undefine STRETCHGRID
#undefine EVOLVINGBOUNDARY
