#!/bin/bash

# Abort on errors
set -eu

# Remove lines after the text below
sed '/Dependencies of FOBJECTS (generated by list_module_deps.sh)/q' makefile > new_makefile

# Append depedencies with the list_module_deps.sh script
./list_module_deps.sh >> new_makefile

mv new_makefile makefile

