#!/bin/bash

# Usage:
# ./update_dependencies.sh            (will report differences)
# ./update_dependencies.sh --inplace  (will update the makefile in-place)
# ./update_dependencies.sh --verbose  (will excplicity tell what's wrong if diff isn't zero)

VERBOSE=NO
INPLACE=NO
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
	-v|--verbose)
	    VERBOSE=YES
	    shift
	    ;;
	-i|--inplace)
	    INPLACE=YES
	    shift
	    ;;
	*)
	    shift
	    ;;
    esac
done
	
# Remove lines after the text below
sed '/Dependencies of FOBJECTS (generated by list_module_deps.sh)/q' makefile > new_makefile || exit 1

# Append depedencies with the list_module_deps.sh script
./list_module_deps.sh >> new_makefile || exit 1

if [ "$INPLACE" == "YES" ]; then
    mv new_makefile makefile
else #dry run
    diff new_makefile makefile
    if [ $? != 0 ]; then
	if [ "$VERBOSE" == "YES" ]; then
	    echo "Hey, did you forget to update dependencies ?"
	    exit 1
	fi
    fi
fi

