#!/bin/bash

# Usage:
# ./update_dependencies.sh
# ./update_dependencies.sh -dry_run (will report differences)

# Abort on non-zero return values
set -eu

if [ $# -eq 1 ]; then
    arg="$1"
else
    arg=""
fi

# Remove lines after the text below
sed '/Dependencies of FOBJECTS (generated by list_module_deps.sh)/q' makefile > new_makefile

# Append depedencies with the list_module_deps.sh script
./list_module_deps.sh >> new_makefile

if [ "$arg" == "-dry_run" ]; then
    diff new_makefile makefile
elif [ "$arg" == "" ]; then
    mv new_makefile makefile
else
    echo "Unknown argument $arg"
    exit 1
fi

