# Add the objects for MHD:

FOBJECTS += eos$F correctaux$F mhdhllc$F hlld$F mhdhlld$F con2prim$F divb$F con2primIso$F fill_gridvars$F fct$F
OBJECTS += eos.o correctaux.o mhdhllc.o hlld.o mhdhlld.o con2prim.o divb.o con2primIso.o fill_gridvars.o fct.o

