#########################################################################
# Everything IO-related goes here:
#########################################################################
FOBJECTS += mod_input_output.t convert.t kracken.t analysis.t collapse.t	\
slice.t
